name: CI

on: [push]

jobs:
  test-run:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5

    - name: Update Homebrew
      run: brew update

    - name: Audit Formula
      run: brew audit --strict ./Formula/macports.rb


    - name: Install Formula
      run: brew install ./Formula/macports.rb --build-from-source --with-dangerous-side-effects

    - name: Test Formula
      run: brew test ./Formula/macports.rb

    - name: Print Version
      run: port version
