name: CI

on: [push]

jobs:
  test-run:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5

    - name: Audit Formula
      run: |
        brew update
        brew audit ./Formula/macports.rb --online

    - name: Install Formula
      run: brew install ./Formula/macports.rb --build-from-source --with-dangerous-side-effects

    - name: Print Version
      run: port version
