name: CI

on: [push]

jobs:
  test-run:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5

    - name: Run tests
      run: |
        brew update
        brew audit --strict ./Formula/macports.rb
        brew test ./Formula/macports.rb
