name: CI

on: [push]

jobs:
  default:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5

    - name: Audit Formula
      run: brew audit Formula/macports.rb --online

    - name: Install Formula
      run: brew install macports
